# Hier sind nur Dummy-Connections verdrahtet.
# Die realen Connections werden gesetzt in ApplicationController.open_connection

# Zu verwendende Konfigurationen (Ramm 25.08.09)
# Ruby Development:
#       adapter: oracle_enhanced
#       database: RAMM
#       username: cust
#       password: noa

# JRuby Development:
#       adapter:  jdbc
#       driver:   oracle.jdbc.driver.OracleDriver
#       url:      jdbc:oracle:thin:@ramm-1.osp-dd.de:1521:RAMM
#       username: sysp
#       password: noa


development:
  adapter: nulldb

#  adapter:  oracle_enhanced
# url:      NULL
#  url:      jdbc:oracle:thin:@0.0.0.0:1521:NULL
#  #url:      jdbc:oracle:thin:@pepsi01.puc.ov.otto.de:1521:NOADB2
#  url:      jdbc:oracle:thin:@ramm.osp-dd.de:1521:RAMM
# driver:   oracle.jdbc.driver.OracleDriver
#  username: dummy
#  password: dummy


# Konkrete Oracle-Test-DB wird erst in test_helper.rb  set_session_test_db_context geswitcht, Parameter werden schon hier gesetzt
test:
  adapter: nulldb

  #adapter:  oracle_enhanced
  #database: LAPRAMM
# url:      jdbc:oracle:thin:@linux-ramm-macpro:1521:RAMMMAC
  #url:      jdbc:oracle:thin:@pepsi01.puc.ov.otto.de:1521:NOADB2
  test_url:      jdbc:oracle:thin:@ramm-1.osp-dd.de:1521:RAMM
  #driver:   oracle.jdbc.driver.OracleDriver
  test_username: noatest
  test_password: noa


test_10.2:
  adapter: nulldb

  test_url:      jdbc:oracle:thin:@ddhpit01.osp-dd.de:1521:GAPR
  test_username: panorama_test
  test_password: panorama_test

test_11.1:
  adapter: nulldb

  test_url:      jdbc:oracle:thin:@ramm-1.osp-dd.de:1521:RAMM
  test_username: noatest
  test_password: noa

test_11.2:
  adapter: nulldb

  test_url:      jdbc:oracle:thin:@ramm.osp-dd.de:1521:RAMM
  test_username: noatest
  test_password: noa

test_12.1:
  adapter: nulldb

  test_url:      jdbc:oracle:thin:@10.211.55.14:1521:orcl.1.localdomain
  test_username: panorama_test
  test_password: panorama_test


# Prod. mit NULLDB betreiben, damit erst mal erfolgreiches Connect zu einer immer vorhandenen DB moeglich ist
# bevor konkrete Oracle-Db ausgewählt wird
production:
  adapter: nulldb

